apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: spark
spec:
  type: Scala
  mode: cluster
  image: "apache/spark:3.5.0"
  imagePullPolicy: IfNotPresent
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.5.0.jar"
  sparkVersion: "3.5.0"

  # Restart policy
  restartPolicy:
    type: Never

  # Driver configuration
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.5.0
      app: spark-pi
    serviceAccount: spark

  # Executor configuration
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.5.0
      app: spark-pi

  # Dependencies (optional)
  deps:
    # jars:
    #   - https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar
    # excludePackages:
    #   - org.slf4j:slf4j-log4j12
